#!/bin/sh

set -e

. ./terraform.conf

lb config noauto \
    --architectures "$ARCH" \
    --mode debian \
    --initramfs live-boot \
    --initsystem systemd \
    --distribution "./$BASECODENAME" \
    --parent-distribution "./$BASECODENAME" \
    --archive-areas "main restricted universe multiverse" \
    --parent-archive-areas "main restricted universe multiverse" \
    --linux-packages linux-image \
    --linux-flavours "generic" \
    --bootappend-live "boot=casper quiet splash" \
    --mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --mirror-chroot-security "$SECURITY_URL" \
    --parent-mirror-chroot-security "$SECURITY_URL" \
    --mirror-binary-security "$SECURITY_URL" \
    --parent-mirror-binary-security "$SECURITY_URL" \
    --mirror-binary "$MIRROR_URL" \
    --parent-mirror-binary "$MIRROR_URL" \
    --keyring-packages ubuntu-keyring \
    --apt-options "--option Acquire::Retries=2 --option Acquire::http::Timeout=45 --yes" \
    --cache-packages false \
    --cache-stages false \
    --uefi-secure-boot enable \
    --binary-image iso-hybrid \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --firmware-binary false \
    --firmware-chroot false \
    --chroot-squashfs-compression-type "xz -Xdict-size 1M -b 1M" \
    --zsync false \
    --security true \
    --updates true \
    --debootstrap-options "--exclude=pinephone-tweaks,mobile-tweaks-common,librem5-tweaks,pinetab-tweaks" \
    --swap-file-path /swapfile \
    --swap-file-size 256 \
    --interactive false \
    --debconf-frontend noninteractive \
    --compression xz \
    --checksums md5 \
    --bootloaders "$BOOTLOADERS" \
    "${@}"